apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-snap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage-class-nas
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: pvc1-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
kind: Pod
apiVersion: v1
metadata:
  name: pvpod-clone
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: pvc-from-snap
  containers:
    - name: task-pv-container
      image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
