kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-volume-claim-sf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: sf-gold
---
kind: Pod
apiVersion: v1
metadata:
  name: pvpod-sf
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: persistent-volume-claim-sf
  containers:
    - name: task-pv-container
      image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
