apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-sf-snap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sf-gold
  resources:
    requests:
      storage: 2Gi
  dataSource:
    name: persistent-volume-claim-sf-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
