kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-solidfire-gold-east
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: solidfire-gold-east
