kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-volume-claim-sf-gold
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: sf-gold
