kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-volume-claim-nas-clone
  annotations:
    trident.netapp.io/cloneFromPVC: persistent-volume-claim-nas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas
