apiVersion: v1
kind: Pod
metadata:
  name: redango
  labels:
    app: web
spec:
  containers:
    - name: backend
      image: redis
      ports:
        - containerPort: 6379
    - name: frontend
      image: django
      ports:
        - containerPort: 8000
  restartPolicy: Always
