apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - port: 80
      targetPort: 9876
      name: webapp.demo.netapp.com
    - port: 443
      targetPort: 9877
      name: secure.demo.netapp.com
  selector:
    app: webapp
