apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - port: 80
      targetPort: 9876
      name: HTTP
    - port: 443
      targetPort: 9877
      name: HTTPS
  selector:
    app: webapp
